//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAllowanceLnk
    {
        [Key]
        public int allow_lnk_id { get; set; }
        public Nullable<int> allowance_id { get; set; }
        public Nullable<decimal> allowance_amnt { get; set; }
        public Nullable<System.DateTime> allowance_sdate { get; set; }
        public Nullable<System.DateTime> allowance_edate { get; set; }
        public Nullable<bool> allowance_perm { get; set; }
        public Nullable<System.DateTime> allowance_month { get; set; }
        public string create_date { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string allowance_notes { get; set; }
    
        public virtual tblAllowance tblAllowance { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
