//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract
    {
        [Key]
        public int cntrct_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string cntrct_title { get; set; }
        public Nullable<System.DateTime> cntrct_sdate { get; set; }
        public Nullable<System.DateTime> cntrct_edate { get; set; }
        public Nullable<int> cntrct_state { get; set; }
        public Nullable<int> cntcrt_typ_id { get; set; }
        public string cntrct_desc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> dpt_id { get; set; }
        public Nullable<int> br_id { get; set; }
        public Nullable<int> pos_id { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblContractType tblContractType { get; set; }
        public virtual tblContractState tblContractState { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblPosition tblPosition { get; set; }
    }
}
