//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractState
    {
        public tblContractState()
        {
            this.tblContracts = new HashSet<tblContract>();
        }

        [Key]
        public int cntrct_st_id { get; set; }
        public string cntrct_state { get; set; }
        public string cntrct_st_desc { get; set; }
    
        public virtual ICollection<tblContract> tblContracts { get; set; }
    }
}
