//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeContact
    {
        [Key]
        public int cnt_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string emp_strt { get; set; }
        public string emp_nghbhd { get; set; }
        public Nullable<int> emp_city { get; set; }
        public Nullable<int> emp_province { get; set; }
        public string emp_phone { get; set; }
        public string emp_mobile { get; set; }
        public string emp_kin { get; set; }
        public string emp_kin_add { get; set; }
        public string emp_kin_ph { get; set; }
        public Nullable<int> rel_id { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblRelationship tblRelationship { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblProvince tblProvince { get; set; }
    }
}
