//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.tblPositionHistories = new HashSet<tblPositionHistory>();
            this.tblUsers = new HashSet<tblUser>();
            this.tblLeaves = new HashSet<tblLeave>();
            this.tblLvUsages = new HashSet<tblLvUsage>();
            this.tblContracts = new HashSet<tblContract>();
            this.tblAllowanceLnks = new HashSet<tblAllowanceLnk>();
            this.tblDeductionLnks = new HashSet<tblDeductionLnk>();
            this.tblEmployeeContacts = new HashSet<tblEmployeeContact>();
            this.tblPayrolls = new HashSet<tblPayroll>();
            this.tblWkshftLinks = new HashSet<tblWkshftLink>();
            this.tblTrainings = new HashSet<tblTraining>();
            this.tblDocuments = new HashSet<tblDocument>();
            this.tblDependants = new HashSet<tblDependant>();
            this.tblEducations = new HashSet<tblEducation>();
            this.tblWorks = new HashSet<tblWork>();
            this.tblAchievements = new HashSet<tblAchievement>();
            this.tblKPIs = new HashSet<tblKPI>();
        }

        [Key]

        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_lname { get; set; }
        public string emp_email { get; set; }
        public Nullable<int> emp_branch { get; set; }
        public Nullable<int> emp_dpt { get; set; }
        public Nullable<int> emp_status { get; set; }
        public Nullable<System.DateTime> emp_bDate { get; set; }
        public Nullable<System.DateTime> emp_jDate { get; set; }
        public Nullable<System.DateTime> emp_cDate { get; set; }
        public Nullable<int> emp_pos_id { get; set; }
        public string emp_id_num { get; set; }
        public string emp_ec_num { get; set; }
        public string emp_nation { get; set; }
        public Nullable<int> emp_state { get; set; }
        public Nullable<int> img_id { get; set; }
        public Nullable<int> emp_sex { get; set; }
        public Nullable<int> emp_marital { get; set; }
        public Nullable<int> emp_sal { get; set; }
        public string emp_mid_names { get; set; }
        public string emp_passport_num { get; set; }
        public Nullable<System.DateTime> emp_passport_date { get; set; }
        public string emp_drv_num { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblEmployeeStatu tblEmployeeStatu { get; set; }
        public virtual ICollection<tblPositionHistory> tblPositionHistories { get; set; }
        public virtual ICollection<tblUser> tblUsers { get; set; }
        public virtual tblPosition tblPosition { get; set; }
        //public virtual tblEmployee tblEmployees1 { get; set; }
        //public virtual tblEmployee tblEmployee1 { get; set; }
        public virtual tblEmplStatu tblEmplStatu { get; set; }
        public virtual tblImage tblImage { get; set; }
        public virtual ICollection<tblLeave> tblLeaves { get; set; }
        public virtual ICollection<tblLvUsage> tblLvUsages { get; set; }
        public virtual tblMarital tblMarital { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual ICollection<tblContract> tblContracts { get; set; }
        public virtual ICollection<tblAllowanceLnk> tblAllowanceLnks { get; set; }
        public virtual ICollection<tblDeductionLnk> tblDeductionLnks { get; set; }
        public virtual ICollection<tblEmployeeContact> tblEmployeeContacts { get; set; }
        public virtual tblSalutation tblSalutation { get; set; }
        public virtual ICollection<tblPayroll> tblPayrolls { get; set; }
        public virtual ICollection<tblWkshftLink> tblWkshftLinks { get; set; }
        public virtual ICollection<tblTraining> tblTrainings { get; set; }
        public virtual ICollection<tblDocument> tblDocuments { get; set; }
        public virtual ICollection<tblDependant> tblDependants { get; set; }
        public virtual ICollection<tblEducation> tblEducations { get; set; }
        public virtual ICollection<tblWork> tblWorks { get; set; }
        public virtual ICollection<tblAchievement> tblAchievements { get; set; }
        public virtual ICollection<tblKPI> tblKPIs { get; set; }
    }
}
