//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobLevel
    {
        public tblJobLevel()
        {
            this.tblPositions = new HashSet<tblPosition>();
        }

        [Key]
        public int lvl_id { get; set; }
        public string lvl_title { get; set; }
        public string lvl_desc { get; set; }
    
        public virtual ICollection<tblPosition> tblPositions { get; set; }
    }
}
