//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLvUsage
    {
        [Key]
        public int lv_u_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> lv_id { get; set; }
        public Nullable<System.DateTime> lv_sdate { get; set; }
        public Nullable<System.DateTime> lv_edate { get; set; }
        public Nullable<decimal> lv_days { get; set; }
        public Nullable<decimal> lv_bal { get; set; }
        public string lv_state { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblLeave tblLeave { get; set; }
    }
}
