//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProvince
    {
        public tblProvince()
        {
            this.tblCities = new HashSet<tblCity>();
            this.tblEmployeeContacts = new HashSet<tblEmployeeContact>();
        }

        [Key]

        public int prov_id { get; set; }
        public string prov_name { get; set; }
    
        public virtual ICollection<tblCity> tblCities { get; set; }
        public virtual ICollection<tblEmployeeContact> tblEmployeeContacts { get; set; }
    }
}
