//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTraining
    {
        [Key]
        public int tr_id { get; set; }
        public int emp_id { get; set; }
        public int course_id { get; set; }
        public Nullable<System.DateTime> tr_sdate { get; set; }
        public Nullable<System.DateTime> tr_edate { get; set; }
        public string tr_status { get; set; }
        public string tr_score { get; set; }
        public string tr_comments { get; set; }
        public Nullable<int> tr_sess_id { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblTrainingSession tblTrainingSession { get; set; }
    }
}
