//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Hrm_SystemCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingSession
    {
        public tblTrainingSession()
        {
            this.tblTrainings = new HashSet<tblTraining>();
        }

        [Key]
        public int tr_sess_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<System.DateTime> tr_sdate { get; set; }
        public Nullable<System.DateTime> tr_edate { get; set; }
        public string tr_sess_name { get; set; }
        public string tr_sess_desc { get; set; }
        public string tr_sess_status { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        public virtual ICollection<tblTraining> tblTrainings { get; set; }
    }
}
