// <auto-generated />
using System;
using Hrm_SystemCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hrm_SystemCore.Migrations
{
    [DbContext(typeof(HRMEntities))]
    [Migration("20231228205650_Identity-Init")]
    partial class IdentityInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hrm_SystemCore.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblAchievement", b =>
                {
                    b.Property<int>("achvt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("achvt_id"));

                    b.Property<string>("achvt_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("achvt_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("achvt_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.HasKey("achvt_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblAchievements");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblAllowance", b =>
                {
                    b.Property<int>("allowance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("allowance_id"));

                    b.Property<string>("allowance_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allowance_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allowance_perc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("allowance_value")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("allowance_id");

                    b.ToTable("tblAllowances");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblAllowanceLnk", b =>
                {
                    b.Property<int>("allow_lnk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("allow_lnk_id"));

                    b.Property<decimal?>("allowance_amnt")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("allowance_edate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("allowance_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("allowance_month")
                        .HasColumnType("datetime2");

                    b.Property<string>("allowance_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("allowance_perm")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("allowance_sdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblAllowanceallowance_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.HasKey("allow_lnk_id");

                    b.HasIndex("tblAllowanceallowance_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblAllowanceLnks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblBank", b =>
                {
                    b.Property<int>("bnk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bnk_id"));

                    b.Property<string>("bnk_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bnk_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bnk_id");

                    b.ToTable("tblBanks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblBranch", b =>
                {
                    b.Property<int>("br_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("br_id"));

                    b.Property<string>("br_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("br_contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("br_descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("br_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("br_id");

                    b.ToTable("tblBranches");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCity", b =>
                {
                    b.Property<int>("cty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cty_id"));

                    b.Property<string>("cty_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("prov_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblProvinceprov_id")
                        .HasColumnType("int");

                    b.HasKey("cty_id");

                    b.HasIndex("tblProvinceprov_id");

                    b.ToTable("tblCities");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblContract", b =>
                {
                    b.Property<int>("cntrct_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cntrct_id"));

                    b.Property<int?>("br_id")
                        .HasColumnType("int");

                    b.Property<int?>("cntcrt_typ_id")
                        .HasColumnType("int");

                    b.Property<string>("cntrct_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("cntrct_edate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("cntrct_sdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("cntrct_state")
                        .HasColumnType("int");

                    b.Property<string>("cntrct_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("dpt_id")
                        .HasColumnType("int");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("pos_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblBranchbr_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblContractStatecntrct_st_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblContractTypecntcrt_typ_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblDepartmentdpt_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblPositionpos_id")
                        .HasColumnType("int");

                    b.HasKey("cntrct_id");

                    b.HasIndex("tblBranchbr_id");

                    b.HasIndex("tblContractStatecntrct_st_id");

                    b.HasIndex("tblContractTypecntcrt_typ_id");

                    b.HasIndex("tblDepartmentdpt_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblPositionpos_id");

                    b.ToTable("tblContracts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblContractState", b =>
                {
                    b.Property<int>("cntrct_st_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cntrct_st_id"));

                    b.Property<string>("cntrct_st_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cntrct_state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cntrct_st_id");

                    b.ToTable("tblContractStates");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblContractType", b =>
                {
                    b.Property<int>("cntcrt_typ_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cntcrt_typ_id"));

                    b.Property<string>("cntrct_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cntrct_typ")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cntcrt_typ_id");

                    b.ToTable("tblContractTypes");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCours", b =>
                {
                    b.Property<int>("course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("course_id"));

                    b.Property<string>("course_descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_dur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_nm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tblCourseTypetype_id")
                        .HasColumnType("int");

                    b.Property<int>("type_id")
                        .HasColumnType("int");

                    b.HasKey("course_id");

                    b.HasIndex("tblCourseTypetype_id");

                    b.ToTable("tblCourses");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCourseType", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("type_id"));

                    b.Property<string>("typ_descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("type_id");

                    b.ToTable("tblCourseTypes");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDeduction", b =>
                {
                    b.Property<int>("deduction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deduction_id"));

                    b.Property<string>("deduction_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deduction_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deduction_perc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("deduction_value")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("deduction_id");

                    b.ToTable("tblDeductions");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDeductionLnk", b =>
                {
                    b.Property<int>("ded_lnk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ded_lnk_id"));

                    b.Property<string>("create_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("deduction_amnt")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("deduction_edate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deduction_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deduction_mnth")
                        .HasColumnType("datetime2");

                    b.Property<string>("deduction_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("deduction_permanent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("deduction_sdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblDeductiondeduction_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.HasKey("ded_lnk_id");

                    b.HasIndex("tblDeductiondeduction_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblDeductionLnks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDepartment", b =>
                {
                    b.Property<int>("dpt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dpt_id"));

                    b.Property<string>("dpt_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dpt_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dpt_id");

                    b.ToTable("tblDepartments");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDependant", b =>
                {
                    b.Property<int>("dep_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dep_id"));

                    b.Property<DateTime?>("dep_dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("dep_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dep_rltn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.HasKey("dep_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblDependants");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDocument", b =>
                {
                    b.Property<int>("doc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doc_id"));

                    b.Property<DateTime?>("doc_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("doc_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doc_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.HasKey("doc_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblDocuments");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEduLevel", b =>
                {
                    b.Property<int>("edu_lv_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("edu_lv_id"));

                    b.Property<string>("edu_lv_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("edu_lv_id");

                    b.ToTable("tblEduLevels");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEducation", b =>
                {
                    b.Property<int>("edu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("edu_id"));

                    b.Property<string>("edu_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("edu_edate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("edu_lvl_id")
                        .HasColumnType("int");

                    b.Property<string>("edu_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edu_qlfcn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edu_score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("edu_sdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEduLeveledu_lv_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.HasKey("edu_id");

                    b.HasIndex("tblEduLeveledu_lv_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblEducations");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmplStatu", b =>
                {
                    b.Property<int>("stat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stat_id"));

                    b.Property<string>("stat_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stat_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stat_id");

                    b.ToTable("tblEmplStatus");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmployee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_id"));

                    b.Property<DateTime?>("emp_bDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("emp_branch")
                        .HasColumnType("int");

                    b.Property<DateTime?>("emp_cDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("emp_dpt")
                        .HasColumnType("int");

                    b.Property<string>("emp_drv_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_ec_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_id_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("emp_jDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("emp_lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_marital")
                        .HasColumnType("int");

                    b.Property<string>("emp_mid_names")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("emp_passport_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("emp_passport_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_pos_id")
                        .HasColumnType("int");

                    b.Property<int?>("emp_sal")
                        .HasColumnType("int");

                    b.Property<int?>("emp_sex")
                        .HasColumnType("int");

                    b.Property<int?>("emp_state")
                        .HasColumnType("int");

                    b.Property<int?>("emp_status")
                        .HasColumnType("int");

                    b.Property<int?>("img_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblBranchbr_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblDepartmentdpt_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmplStatustat_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeStatuempst_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblGenderemp_sx_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblImageimg_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblMaritalmarital_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblPositionpos_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblSalutationsal_id")
                        .HasColumnType("int");

                    b.HasKey("emp_id");

                    b.HasIndex("tblBranchbr_id");

                    b.HasIndex("tblDepartmentdpt_id");

                    b.HasIndex("tblEmplStatustat_id");

                    b.HasIndex("tblEmployeeStatuempst_id");

                    b.HasIndex("tblGenderemp_sx_id");

                    b.HasIndex("tblImageimg_id");

                    b.HasIndex("tblMaritalmarital_id");

                    b.HasIndex("tblPositionpos_id");

                    b.HasIndex("tblSalutationsal_id");

                    b.ToTable("tblEmployees");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmployeeContact", b =>
                {
                    b.Property<int>("cnt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cnt_id"));

                    b.Property<int?>("emp_city")
                        .HasColumnType("int");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<string>("emp_kin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_kin_add")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_kin_ph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_nghbhd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emp_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_province")
                        .HasColumnType("int");

                    b.Property<string>("emp_strt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rel_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblCitycty_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblProvinceprov_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblRelationshiprel_id")
                        .HasColumnType("int");

                    b.HasKey("cnt_id");

                    b.HasIndex("tblCitycty_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblProvinceprov_id");

                    b.HasIndex("tblRelationshiprel_id");

                    b.ToTable("tblEmployeeContacts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmployeeStatu", b =>
                {
                    b.Property<int>("empst_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empst_id"));

                    b.Property<string>("empst_descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empst_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("empst_id");

                    b.ToTable("tblEmployeeStatus");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblGender", b =>
                {
                    b.Property<int>("emp_sx_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_sx_id"));

                    b.Property<string>("emp_sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_sx_id");

                    b.ToTable("tblGenders");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblImage", b =>
                {
                    b.Property<int>("img_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("img_id"));

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<byte[]>("img_data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("img_desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("img_id");

                    b.ToTable("tblImages");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblJobLevel", b =>
                {
                    b.Property<int>("lvl_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lvl_id"));

                    b.Property<string>("lvl_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lvl_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lvl_id");

                    b.ToTable("tblJobLevels");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblKPI", b =>
                {
                    b.Property<int>("kpi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kpi_id"));

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<string>("kpi_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("kpi_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("kpi_prd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kpi_score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kpi_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.HasKey("kpi_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblKPIs");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblLeave", b =>
                {
                    b.Property<int>("lv_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lv_id"));

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("lv_bal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("lv_period")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lvtyp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblLvTypelvtyp_id")
                        .HasColumnType("int");

                    b.HasKey("lv_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblLvTypelvtyp_id");

                    b.ToTable("tblLeaves");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblLvType", b =>
                {
                    b.Property<int>("lvtyp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lvtyp_id"));

                    b.Property<decimal?>("lvtyp_num")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("lvtyp_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lvtyp_id");

                    b.ToTable("tblLvTypes");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblLvUsage", b =>
                {
                    b.Property<int>("lv_u_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lv_u_id"));

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("lv_bal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("lv_days")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("lv_edate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lv_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lv_sdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("lv_state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblLeavelv_id")
                        .HasColumnType("int");

                    b.HasKey("lv_u_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblLeavelv_id");

                    b.ToTable("tblLvUsages");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblMarital", b =>
                {
                    b.Property<int>("marital_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("marital_id"));

                    b.Property<string>("marital_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("marital_id");

                    b.ToTable("tblMaritals");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblOrganisation", b =>
                {
                    b.Property<int>("org_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("org_id"));

                    b.Property<string>("org_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("org_descr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("org_logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("org_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("org_phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("org_id");

                    b.ToTable("tblOrganisations");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPayMethod", b =>
                {
                    b.Property<int>("pay_method_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pay_method_id"));

                    b.Property<string>("pay_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pay_method_id");

                    b.ToTable("tblPayMethods");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPayroll", b =>
                {
                    b.Property<int>("pay_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pay_id"));

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("emp_Salary")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("emp_acc_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("emp_bnk")
                        .HasColumnType("int");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("emp_method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("pay_end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("pay_start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("pay_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tblBankbnk_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblPayMethodpay_method_id")
                        .HasColumnType("int");

                    b.HasKey("pay_id");

                    b.HasIndex("tblBankbnk_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblPayMethodpay_method_id");

                    b.ToTable("tblPayrolls");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPosition", b =>
                {
                    b.Property<int>("pos_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pos_id"));

                    b.Property<int?>("dp_id")
                        .HasColumnType("int");

                    b.Property<int?>("lvl_id")
                        .HasColumnType("int");

                    b.Property<string>("pos_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pos_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tblDepartmentdpt_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblJobLevellvl_id")
                        .HasColumnType("int");

                    b.HasKey("pos_id");

                    b.HasIndex("tblDepartmentdpt_id");

                    b.HasIndex("tblJobLevellvl_id");

                    b.ToTable("tblPositions");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPositionHistory", b =>
                {
                    b.Property<int>("ph_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ph_id"));

                    b.Property<int?>("br_id")
                        .HasColumnType("int");

                    b.Property<int?>("dpt_id")
                        .HasColumnType("int");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ph_eDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ph_sDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ph_sal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("pos_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblBranchbr_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblDepartmentdpt_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblPositionpos_id")
                        .HasColumnType("int");

                    b.HasKey("ph_id");

                    b.HasIndex("tblBranchbr_id");

                    b.HasIndex("tblDepartmentdpt_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblPositionpos_id");

                    b.ToTable("tblPositionHistories");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblProvince", b =>
                {
                    b.Property<int>("prov_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prov_id"));

                    b.Property<string>("prov_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("prov_id");

                    b.ToTable("tblProvinces");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblRelationship", b =>
                {
                    b.Property<int>("rel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rel_id"));

                    b.Property<string>("rel_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rel_id");

                    b.ToTable("tblRelationships");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblSalutation", b =>
                {
                    b.Property<int>("sal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sal_id"));

                    b.Property<string>("sal_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sal_id");

                    b.ToTable("tblSalutations");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblTraining", b =>
                {
                    b.Property<int>("tr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tr_id"));

                    b.Property<int>("course_id")
                        .HasColumnType("int");

                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblCourscourse_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblTrainingSessiontr_sess_id")
                        .HasColumnType("int");

                    b.Property<string>("tr_comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tr_edate")
                        .HasColumnType("datetime2");

                    b.Property<string>("tr_score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tr_sdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("tr_sess_id")
                        .HasColumnType("int");

                    b.Property<string>("tr_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tr_id");

                    b.HasIndex("tblCourscourse_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblTrainingSessiontr_sess_id");

                    b.ToTable("tblTrainings");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblTrainingSession", b =>
                {
                    b.Property<int>("tr_sess_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tr_sess_id"));

                    b.Property<int?>("course_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblCourscourse_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("tr_edate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("tr_sdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("tr_sess_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tr_sess_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tr_sess_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tr_sess_id");

                    b.HasIndex("tblCourscourse_id");

                    b.ToTable("tblTrainingSessions");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblUser", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblUsers");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblWkshftLink", b =>
                {
                    b.Property<int>("wk_lnk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("wk_lnk_id"));

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblWorkshiftwkshft_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("wk_lnk_eDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("wk_lnk_stDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("wk_lnk_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("wkshft_id")
                        .HasColumnType("int");

                    b.HasKey("wk_lnk_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.HasIndex("tblWorkshiftwkshft_id");

                    b.ToTable("tblWkshftLinks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblWork", b =>
                {
                    b.Property<int>("wrk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("wrk_id"));

                    b.Property<int?>("emp_id")
                        .HasColumnType("int");

                    b.Property<int?>("tblEmployeeemp_id")
                        .HasColumnType("int");

                    b.Property<string>("wk_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wk_company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wk_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("wk_edate")
                        .HasColumnType("datetime2");

                    b.Property<string>("wk_position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("wk_sdate")
                        .HasColumnType("datetime2");

                    b.HasKey("wrk_id");

                    b.HasIndex("tblEmployeeemp_id");

                    b.ToTable("tblWorks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblWorkshift", b =>
                {
                    b.Property<int>("wkshft_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("wkshft_id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("inputter")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("wkshft_brk_from")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("wkshft_brk_to")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("wkshft_from")
                        .HasColumnType("time");

                    b.Property<int?>("wkshft_hrs")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("wkshft_lunch_from")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("wkshft_lunch_to")
                        .HasColumnType("time");

                    b.Property<string>("wkshft_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wkshft_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("wkshft_to")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("wkshft_xtrabrk_from")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("wkshft_xtrabrk_to")
                        .HasColumnType("time");

                    b.HasKey("wkshft_id");

                    b.ToTable("tblWorkshifts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblgrade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblgrades");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.Users", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblAchievement", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblAchievements")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblAllowanceLnk", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblAllowance", "tblAllowance")
                        .WithMany("tblAllowanceLnks")
                        .HasForeignKey("tblAllowanceallowance_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblAllowanceLnks")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblAllowance");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCity", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblProvince", "tblProvince")
                        .WithMany("tblCities")
                        .HasForeignKey("tblProvinceprov_id");

                    b.Navigation("tblProvince");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblContract", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblBranch", "tblBranch")
                        .WithMany("tblContracts")
                        .HasForeignKey("tblBranchbr_id");

                    b.HasOne("Hrm_SystemCore.Models.tblContractState", "tblContractState")
                        .WithMany("tblContracts")
                        .HasForeignKey("tblContractStatecntrct_st_id");

                    b.HasOne("Hrm_SystemCore.Models.tblContractType", "tblContractType")
                        .WithMany("tblContracts")
                        .HasForeignKey("tblContractTypecntcrt_typ_id");

                    b.HasOne("Hrm_SystemCore.Models.tblDepartment", "tblDepartment")
                        .WithMany("tblContracts")
                        .HasForeignKey("tblDepartmentdpt_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblContracts")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblPosition", "tblPosition")
                        .WithMany("tblContracts")
                        .HasForeignKey("tblPositionpos_id");

                    b.Navigation("tblBranch");

                    b.Navigation("tblContractState");

                    b.Navigation("tblContractType");

                    b.Navigation("tblDepartment");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblPosition");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCours", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblCourseType", "tblCourseType")
                        .WithMany("tblCourses")
                        .HasForeignKey("tblCourseTypetype_id");

                    b.Navigation("tblCourseType");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDeductionLnk", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblDeduction", "tblDeduction")
                        .WithMany("tblDeductionLnks")
                        .HasForeignKey("tblDeductiondeduction_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblDeductionLnks")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblDeduction");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDependant", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblDependants")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDocument", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblDocuments")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEducation", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEduLevel", "tblEduLevel")
                        .WithMany("tblEducations")
                        .HasForeignKey("tblEduLeveledu_lv_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblEducations")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblEduLevel");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmployee", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblBranch", "tblBranch")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblBranchbr_id");

                    b.HasOne("Hrm_SystemCore.Models.tblDepartment", "tblDepartment")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblDepartmentdpt_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmplStatu", "tblEmplStatu")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblEmplStatustat_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployeeStatu", "tblEmployeeStatu")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblEmployeeStatuempst_id");

                    b.HasOne("Hrm_SystemCore.Models.tblGender", "tblGender")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblGenderemp_sx_id");

                    b.HasOne("Hrm_SystemCore.Models.tblImage", "tblImage")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblImageimg_id");

                    b.HasOne("Hrm_SystemCore.Models.tblMarital", "tblMarital")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblMaritalmarital_id");

                    b.HasOne("Hrm_SystemCore.Models.tblPosition", "tblPosition")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblPositionpos_id");

                    b.HasOne("Hrm_SystemCore.Models.tblSalutation", "tblSalutation")
                        .WithMany("tblEmployees")
                        .HasForeignKey("tblSalutationsal_id");

                    b.Navigation("tblBranch");

                    b.Navigation("tblDepartment");

                    b.Navigation("tblEmplStatu");

                    b.Navigation("tblEmployeeStatu");

                    b.Navigation("tblGender");

                    b.Navigation("tblImage");

                    b.Navigation("tblMarital");

                    b.Navigation("tblPosition");

                    b.Navigation("tblSalutation");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmployeeContact", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblCity", "tblCity")
                        .WithMany("tblEmployeeContacts")
                        .HasForeignKey("tblCitycty_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblEmployeeContacts")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblProvince", "tblProvince")
                        .WithMany("tblEmployeeContacts")
                        .HasForeignKey("tblProvinceprov_id");

                    b.HasOne("Hrm_SystemCore.Models.tblRelationship", "tblRelationship")
                        .WithMany("tblEmployeeContacts")
                        .HasForeignKey("tblRelationshiprel_id");

                    b.Navigation("tblCity");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblProvince");

                    b.Navigation("tblRelationship");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblKPI", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblKPIs")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblLeave", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblLeaves")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblLvType", "tblLvType")
                        .WithMany("tblLeaves")
                        .HasForeignKey("tblLvTypelvtyp_id");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblLvType");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblLvUsage", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblLvUsages")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblLeave", "tblLeave")
                        .WithMany("tblLvUsages")
                        .HasForeignKey("tblLeavelv_id");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblLeave");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPayroll", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblBank", "tblBank")
                        .WithMany("tblPayrolls")
                        .HasForeignKey("tblBankbnk_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblPayrolls")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblPayMethod", "tblPayMethod")
                        .WithMany("tblPayrolls")
                        .HasForeignKey("tblPayMethodpay_method_id");

                    b.Navigation("tblBank");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblPayMethod");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPosition", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblDepartment", "tblDepartment")
                        .WithMany("tblPositions")
                        .HasForeignKey("tblDepartmentdpt_id");

                    b.HasOne("Hrm_SystemCore.Models.tblJobLevel", "tblJobLevel")
                        .WithMany("tblPositions")
                        .HasForeignKey("tblJobLevellvl_id");

                    b.Navigation("tblDepartment");

                    b.Navigation("tblJobLevel");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPositionHistory", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblBranch", "tblBranch")
                        .WithMany("tblPositionHistories")
                        .HasForeignKey("tblBranchbr_id");

                    b.HasOne("Hrm_SystemCore.Models.tblDepartment", "tblDepartment")
                        .WithMany("tblPositionHistories")
                        .HasForeignKey("tblDepartmentdpt_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblPositionHistories")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblPosition", "tblPosition")
                        .WithMany("tblPositionHistories")
                        .HasForeignKey("tblPositionpos_id");

                    b.Navigation("tblBranch");

                    b.Navigation("tblDepartment");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblPosition");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblTraining", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblCours", "tblCours")
                        .WithMany("tblTrainings")
                        .HasForeignKey("tblCourscourse_id");

                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblTrainings")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblTrainingSession", "tblTrainingSession")
                        .WithMany("tblTrainings")
                        .HasForeignKey("tblTrainingSessiontr_sess_id");

                    b.Navigation("tblCours");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblTrainingSession");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblTrainingSession", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblCours", "tblCours")
                        .WithMany("tblTrainingSessions")
                        .HasForeignKey("tblCourscourse_id");

                    b.Navigation("tblCours");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblUser", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblUsers")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblWkshftLink", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblWkshftLinks")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.HasOne("Hrm_SystemCore.Models.tblWorkshift", "tblWorkshift")
                        .WithMany("tblWkshftLinks")
                        .HasForeignKey("tblWorkshiftwkshft_id");

                    b.Navigation("tblEmployee");

                    b.Navigation("tblWorkshift");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblWork", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.tblEmployee", "tblEmployee")
                        .WithMany("tblWorks")
                        .HasForeignKey("tblEmployeeemp_id");

                    b.Navigation("tblEmployee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hrm_SystemCore.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Hrm_SystemCore.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblAllowance", b =>
                {
                    b.Navigation("tblAllowanceLnks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblBank", b =>
                {
                    b.Navigation("tblPayrolls");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblBranch", b =>
                {
                    b.Navigation("tblContracts");

                    b.Navigation("tblEmployees");

                    b.Navigation("tblPositionHistories");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCity", b =>
                {
                    b.Navigation("tblEmployeeContacts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblContractState", b =>
                {
                    b.Navigation("tblContracts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblContractType", b =>
                {
                    b.Navigation("tblContracts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCours", b =>
                {
                    b.Navigation("tblTrainingSessions");

                    b.Navigation("tblTrainings");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblCourseType", b =>
                {
                    b.Navigation("tblCourses");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDeduction", b =>
                {
                    b.Navigation("tblDeductionLnks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblDepartment", b =>
                {
                    b.Navigation("tblContracts");

                    b.Navigation("tblEmployees");

                    b.Navigation("tblPositionHistories");

                    b.Navigation("tblPositions");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEduLevel", b =>
                {
                    b.Navigation("tblEducations");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmplStatu", b =>
                {
                    b.Navigation("tblEmployees");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmployee", b =>
                {
                    b.Navigation("tblAchievements");

                    b.Navigation("tblAllowanceLnks");

                    b.Navigation("tblContracts");

                    b.Navigation("tblDeductionLnks");

                    b.Navigation("tblDependants");

                    b.Navigation("tblDocuments");

                    b.Navigation("tblEducations");

                    b.Navigation("tblEmployeeContacts");

                    b.Navigation("tblKPIs");

                    b.Navigation("tblLeaves");

                    b.Navigation("tblLvUsages");

                    b.Navigation("tblPayrolls");

                    b.Navigation("tblPositionHistories");

                    b.Navigation("tblTrainings");

                    b.Navigation("tblUsers");

                    b.Navigation("tblWkshftLinks");

                    b.Navigation("tblWorks");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblEmployeeStatu", b =>
                {
                    b.Navigation("tblEmployees");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblGender", b =>
                {
                    b.Navigation("tblEmployees");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblImage", b =>
                {
                    b.Navigation("tblEmployees");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblJobLevel", b =>
                {
                    b.Navigation("tblPositions");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblLeave", b =>
                {
                    b.Navigation("tblLvUsages");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblLvType", b =>
                {
                    b.Navigation("tblLeaves");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblMarital", b =>
                {
                    b.Navigation("tblEmployees");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPayMethod", b =>
                {
                    b.Navigation("tblPayrolls");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblPosition", b =>
                {
                    b.Navigation("tblContracts");

                    b.Navigation("tblEmployees");

                    b.Navigation("tblPositionHistories");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblProvince", b =>
                {
                    b.Navigation("tblCities");

                    b.Navigation("tblEmployeeContacts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblRelationship", b =>
                {
                    b.Navigation("tblEmployeeContacts");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblSalutation", b =>
                {
                    b.Navigation("tblEmployees");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblTrainingSession", b =>
                {
                    b.Navigation("tblTrainings");
                });

            modelBuilder.Entity("Hrm_SystemCore.Models.tblWorkshift", b =>
                {
                    b.Navigation("tblWkshftLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
