//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeductionLnk
    {
        public int ded_lnk_id { get; set; }
        public Nullable<int> deduction_id { get; set; }
        public Nullable<decimal> deduction_amnt { get; set; }
        public Nullable<System.DateTime> deduction_sdate { get; set; }
        public Nullable<System.DateTime> deduction_edate { get; set; }
        public Nullable<bool> deduction_permanent { get; set; }
        public Nullable<System.DateTime> deduction_mnth { get; set; }
        public string create_date { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string deduction_notes { get; set; }
    
        public virtual tblDeduction tblDeduction { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
