//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public tblImage()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
        }
    
        public int img_id { get; set; }
        public byte[] img_data { get; set; }
        public string img_desc { get; set; }
        public Nullable<int> emp_id { get; set; }
    
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
    }
}
