//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKPI
    {
        public int kpi_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string kpi_score { get; set; }
        public string kpi_prd { get; set; }
        public Nullable<System.DateTime> kpi_date { get; set; }
        public string kpi_comment { get; set; }
        public string kpi_title { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
