//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLvType
    {
        public tblLvType()
        {
            this.tblLeaves = new HashSet<tblLeave>();
        }
    
        public int lvtyp_id { get; set; }
        public string lvtyp_title { get; set; }
        public Nullable<decimal> lvtyp_num { get; set; }
    
        public virtual ICollection<tblLeave> tblLeaves { get; set; }
    }
}
