//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrganisation
    {
        public int org_id { get; set; }
        public string org_name { get; set; }
        public string org_logo { get; set; }
        public string org_address { get; set; }
        public string org_descr { get; set; }
        public string org_phone { get; set; }
    }
}
