//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayroll
    {
        public int pay_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<decimal> emp_Salary { get; set; }
        public Nullable<int> emp_bnk { get; set; }
        public Nullable<int> emp_method { get; set; }
        public string emp_acc_num { get; set; }
        public Nullable<System.DateTime> pay_start_date { get; set; }
        public Nullable<System.DateTime> pay_end_date { get; set; }
        public string pay_status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual tblBank tblBank { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblPayMethod tblPayMethod { get; set; }
    }
}
