//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPosition
    {
        public tblPosition()
        {
            this.tblPositionHistories = new HashSet<tblPositionHistory>();
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblContracts = new HashSet<tblContract>();
        }
    
        public int pos_id { get; set; }
        public Nullable<int> lvl_id { get; set; }
        public string pos_title { get; set; }
        public string pos_desc { get; set; }
        public Nullable<int> dp_id { get; set; }
    
        public virtual ICollection<tblPositionHistory> tblPositionHistories { get; set; }
        public virtual tblJobLevel tblJobLevel { get; set; }
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual ICollection<tblContract> tblContracts { get; set; }
    }
}
