//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWork
    {
        public int wrk_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string wk_company { get; set; }
        public string wk_position { get; set; }
        public Nullable<System.DateTime> wk_sdate { get; set; }
        public Nullable<System.DateTime> wk_edate { get; set; }
        public string wk_desc { get; set; }
        public string wk_comment { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
