//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract
    {
        public int cntrct_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string cntrct_title { get; set; }
        public Nullable<System.DateTime> cntrct_sdate { get; set; }
        public Nullable<System.DateTime> cntrct_edate { get; set; }
        public string cntrct_state { get; set; }
        public Nullable<int> cntcrt_typ_id { get; set; }
        public string cntrct_desc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblContractType tblContractType { get; set; }
    }
}
