//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public tblDepartment()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblPositionHistories = new HashSet<tblPositionHistory>();
            this.tblPositions = new HashSet<tblPosition>();
        }
    
        public int dpt_id { get; set; }
        public string dpt_name { get; set; }
        public string dpt_desc { get; set; }
    
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual ICollection<tblPositionHistory> tblPositionHistories { get; set; }
        public virtual ICollection<tblPosition> tblPositions { get; set; }
    }
}
