//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeduction
    {
        public tblDeduction()
        {
            this.tblDeductionLnks = new HashSet<tblDeductionLnk>();
        }
    
        public int deduction_id { get; set; }
        public string deduction_name { get; set; }
        public Nullable<decimal> deduction_value { get; set; }
        public string deduction_perc { get; set; }
        public string deduction_desc { get; set; }
    
        public virtual ICollection<tblDeductionLnk> tblDeductionLnks { get; set; }
    }
}
