//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmplStatu
    {
        public tblEmplStatu()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
        }
    
        public int stat_id { get; set; }
        public string stat_name { get; set; }
        public string stat_desc { get; set; }
    
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
    }
}
