//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProvince
    {
        public tblProvince()
        {
            this.tblCities = new HashSet<tblCity>();
        }
    
        public int prov_id { get; set; }
        public string prov_name { get; set; }
    
        public virtual ICollection<tblCity> tblCities { get; set; }
    }
}
